import { Product, ProductType } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    title: 'Quantum Financial Spreadsheet Suite',
    description: 'Advanced predictive modeling for crypto and forex markets using entangled logic algorithms.',
    price: 49.99,
    type: ProductType.SPREADSHEET,
    size: '45MB',
    tags: ['Finance', 'Excel', 'Prediction'],
    imageUrl: 'https://picsum.photos/400/400?random=1',
    dnaSignature: 'DNA-884-X99-ALPHA',
    generatedBy: 'Cortana-Finance-Bot'
  },
  {
    id: 'prod-002',
    title: 'Neon Cyberpunk Logo Bundle (400GB)',
    description: 'A massive collection of vector-based logo templates generated by neural style transfer agents.',
    price: 199.00,
    type: ProductType.LOGO_BUNDLE,
    size: '400GB',
    tags: ['Design', 'Vector', 'Cyberpunk'],
    imageUrl: 'https://picsum.photos/400/400?random=2',
    dnaSignature: 'DNA-772-Y22-OMEGA',
    generatedBy: 'Design-Core-Agent-7'
  },
  {
    id: 'prod-003',
    title: 'AGI Prompt Engineering Masterclass',
    description: 'Ebook guide to communicating with Level 5 autonomous agents.',
    price: 24.50,
    type: ProductType.EBOOK,
    size: '12MB',
    tags: ['Education', 'AI', 'Prompting'],
    imageUrl: 'https://picsum.photos/400/400?random=3',
    dnaSignature: 'DNA-110-Z01-PRIME',
    generatedBy: 'Teacher-Bot-v9'
  },
  {
    id: 'prod-004',
    title: 'Neural Network Optimization Scripts',
    description: 'Python scripts for optimizing local LLM inference speeds by 400%.',
    price: 89.00,
    type: ProductType.AI_MODEL,
    size: '2GB',
    tags: ['Code', 'Python', 'Optimization'],
    imageUrl: 'https://picsum.photos/400/400?random=4',
    dnaSignature: 'DNA-555-K99-ROOT',
    generatedBy: 'Dev-Ops-Agent-00'
  }
];

export const NAV_LINKS = [
  { name: 'Nexus Market', id: 'market' },
  { name: 'AI Generator Lab', id: 'lab' },
  { name: 'Quantum Dashboard', id: 'dashboard' },
  { name: 'Origin DNA Bank', id: 'dna' },
];